// 2026-05-29 16:37



apply from: "config.gradle"
apply from: "dependencies.gradle"

buildscript {
    repositories {
        // 腾讯云镜像（优先使用）
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/google/' }

        // 其他必要仓库
        maven { url "https://mvn.mob.com/android" }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url "https://www.jitpack.io" }
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            credentials {
                username 'braintree_team_sdk'
                password 'AKCp8jQcoDy2hxSWhDAUQKXLDPDx6NYRkqrgFLRc3qDrayg6rrCbJpsKKyMwaykVL8FWusJpp'
            }
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
        classpath "com.mob.sdk:MobSDK:2018.0319.1724"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath "com.google.protobuf:protobuf-gradle-plugin:0.9.4"
    }
}

allprojects {
    repositories {
        // 腾讯云镜像（优先使用）
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/google/' }

        // 其他必要仓库
        maven { url "https://mvn.mob.com/android" }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url "https://www.jitpack.io" }
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            credentials {
                username 'braintree_team_sdk'
                password 'AKCp8jQcoDy2hxSWhDAUQKXLDPDx6NYRkqrgFLRc3qDrayg6rrCbJpsKKyMwaykVL8FWusJpp'
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}